### ISSUE TITLE
Imgur oembed endpoint has changed

### ISSUE THREAD

**Issue by jdrydn** [jdrydn/yoem#2]
So, currently [`https://imgur.com/f4HZrzu`](https://imgur.com/f4HZrzu) results in:

```json
{
  "error": true,
  "code": null,
  "name": "RequestError",
  "message": "Non-200 response returned: 404",
  "status": 404
}
```

**Comment by jdrydn** [comment]
Upon further inspection, `https://api.imgur.com/oembed.json?url=https://i.imgur.com/f4HZrzu.jpg` now results in:

```json
{
  "data": {
    "error": "Invalid URL - no hash or ID",
    "request": "/oembed.json",
    "method": "GET"
  },
  "success": false,
  "status": 404
}
```

It seems the API has silently updated to now want: `https://api.imgur.com/oembed.json?url=f4HZrzu`

This breaks the Oembed standard, so Imgur is now added to the list of companies who ignore the standardised format and require additional legwork to support.

**Comment by BobStein** [comment]
Is it possible they merely stopped supporting the `i.` in `i.imgur.com`?

This seems to work:  https://api.imgur.com/oembed.json?url=https://imgur.com/f4HZrzu

producing:

```
{
    "version": "1.0",
    "type": "rich",
    "provider_name": "Imgur",
    "provider_url": "https:\/\/imgur.com",
    "width": 540,
    "height": 500,
    "html": "<blockquote class=\"imgur-embed-pub\" lang=\"en\" data-id=\"f4HZrzu\"><a href=\"https:\/\/imgur.com\/f4HZrzu\">View post on imgur.com<\/a><\/blockquote><script async src=\"\/\/s.imgur.com\/min\/embed.js\" charset=\"utf-8\"><\/script>"
}
```

**Comment by jdrydn** [comment]
Honestly @BobStein it seems like Imgur don't document their Oembed endpoint, so it's a struggle. Having said that, they seem to support `application/json+oembed` links in their `<head>`:

```html
<link rel="alternate" type="application/json+oembed" href="https://api.imgur.com/oembed.json?url=https://imgur.com/f4HZrzu"/>
```

I will update Yoem to remove the Imgur "service". Yoem will hit the raw URL, find this tag & then hit the Imgur oembed endpoint on its own. From there, it's all on Imgur to keep to the [Oembed spec](https://oembed.com)!

Thanks for bringing this to my attention 👍

**Comment by BobStein** [comment]
Ooh good to know about those link elements @jdrydn.  I see vimeo uses them, but youtube and instagram don't. 

I happened upon your page hunting down oembed vagaries for my own project. It's hard to know where to turn. Noembed.com appears to be waning in upkeep. So I guess I just support one site at a time. Interesting times. Anyway all the best.
